# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: e2e tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install alexa dependencies
      working-directory: alexa/lambda
      run: | 
        npm install
        sudo npm install -g bespoken-tools
    - name: install angular dependencies
      working-directory: angular
      run: npm install 
    - name: run angular unit tests
      working-directory: angular
      run: npm run test:ci
    - name: run alexa unit tests
      working-directory: alexa
      run: |
        export DEBUG=true
        bst test
    - name: start my thai star
      run: docker-compose up --build -d
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
    - name: run Java unit tests
      working-directory: java/mtsj
      run: mvn test
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: beta
    - name: link new chrome browser to /usr/bin/
      run: |
        sudo rm $(which google-chrome)
        sudo ln -s $(which chrome) /usr/bin/google-chrome
    - name: run e2e tests
      working-directory: mrchecker/endtoend-test
      run: |
        mvn test -Dtest=MyThaiStarTest -Dbrowser=ChromeHeadless -Dos=LINUX -DbrowserOptions="binary_location=$(which chrome)"
