# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: e2e tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: beta
    - name: debug
      run: |
        chrome --version
        google-chrome --version
        which chrome
        which google-chrome
        ls $(which chrome)
        ls $(which google-chrome)
        sudo rm $(which chrome)
        sudo ln $(which chrome) /usr/bin/google-chrome
    - name: run tests
      working-directory: mrchecker/endtoend-test
      run: |
        mvn test -Dtest=MyThaiStarTest -Dbrowser=ChromeHeadless -Dos=LINUX -DbrowserOptions="binary_location=$(which chrome)"
